---
  - name: installing and launching filebeat
    hosts: webservers
    remote_user: ansible
    become: yes
    tasks:

    - name: Make directory filebeat
    command: mkdir /etc/filebeat

    - name: download filebeat deb
      command: curl https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb > /etc/filebeat/filebeat-7.4.0-amd64.deb

    - name: install filebeat deb
      command: dpkg -i /etc/filebeat/filebeat-7.4.0-amd64.deb

    - name: drop in filebeat.yml
      copy:
        src: /etc/ansible/files/filebeat-configuration.yml
        dest: /etc/filebeat/filebeat.yml

    - name: enable and configure system module
      command: filebeat modules enable system

    - name: setup filebeat
      command: filebeat setup
      
    - name: start filebeat service
      command: service filebeat start