---
  - name: installing and launching metricbeat
    hosts: webservers
    remote_user: ansible
    become: yes
    tasks:

    - name: Make metricbeat directory
      command: mkdir /etc/metricbeat

    - name: download metricbeat deb
      become: yes
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
        dest: /etc/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: install metricbeat deb
      command: dpkg -i /etc/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: drop in metricbeat.yml
      copy:
        src: /etc/ansible/files/metricbeat-configuration.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: enable and configure docker module
      command: metricbeat modules enable docker

    - name: setup metricbeat
      command: metricbeat setup
      
    - name: start metricbeat service
      command: service metricbeat start